### PR TITLE
refactor(log): fix undefined when loading plugin (use manifest…)

### PR DESCRIPTION
**Pull request by Lisandra-dev**
For some reason (I'm not pretty sure), I needed to reload the settings after their saving in the overriding.

### CODE REVIEW

**Comment by trganda** [comment]
For safety, we should save and reload the setting everytime when set or reset. I have forgot to reload the setting after submit.

**Comment by trganda** [comment]
Btw, for the Reset command, maybe we should use await (save and reload) as the callback of Reset button?

In the previous PR, you have remove the await (save and reload), any reason? (This may leading error setting I think)

**Comment by Lisandra-dev** [comment]
You don't need to await in a checkCallback() (my testing around this doesn't make problem, as in my other plugin)

**Comment by trganda** [comment]
> You don't need to await in a checkCallback() (my testing around this doesn't make problem, as in my other plugin)

Tks for your tips, I have test it and evertything is ok.

**Pull request merged**
